### ISSUE TITLE
Регистрация всех членов команды в slack

### ISSUE THREAD

**Issue by jehy** [mami-drones/group6-robot#6]

**Comment by AriaTaary** [comment]
- [x] Борисов Александр [slack](https://mami-drones.slack.com/messages/@sb.fox/)
- [x] Куликова Арина [slack](https://mami-drones.slack.com/messages/@ariataary/)
- [x] Ильин Павел [slack](https://mami-drones.slack.com/messages/@ilinpavel/)
- [x] Скляр Павел [slack](https://mami-drones.slack.com/messages/@ozpavel/)
- [x] Зайцев Иван [slack](https://mami-drones.slack.com/messages/@izphantom/)
