### ISSUE TITLE
Регистрация всех членов команды в github

### ISSUE THREAD

**Issue by jehy** [mami-drones/group6-robot#7]

**Comment by AriaTaary** [comment]
- [x] Борисов Александр [vk](https://vk.com/skyblue_fox) [gh](https://github.com/sb-fox)
- [x] Куликова Арина [vk](https://vk.com/ariataary) [gh](https://github.com/AriaTaary)
- [x] Ильин Павел [vk](https://vk.com/iliwoody) [gh](https://github.com/IlinPavel)
- [x] Скляр Павел [vk](https://vk.com/pavelsklyar) [gh](https://github.com/ozpavel)
- [x] Зайцев Иван [vk](https://vk.com/izphantom) [gh](https://github.com/IZphantom)
